### ISSUE TITLE
USER STORY: <TITLE>

### ISSUE THREAD

**Issue by Inc21** [Inc21/my-first-agile-project#6]
As a **Administrator** I want to be able to **show fun and social side of the club** so that **potential member can see that its not all hardship and training.**

## Accceptance Criteria:
- Website should include fun and positive images from different events.
- Website should include all club related social media.

## Tasks
- [x] Create picture gallery page.
- [ ] Include all club socials on the page.
- [x] Choose positive and eye cathing hero image on the home page.
